"""Language strings for the UI.

Hindi strings are ASCII-safe transliterations so they render on the default
MicroPython text path without a custom Devanagari font.
"""

from config import DEFAULT_LANGUAGE, SUPPORTED_LANGUAGES


STRINGS = {
    "en": {
        "title": "Weigh Machine",
        "weight": "Weight",
        "profile": "Profile",
        "gravity": "g",
        "menu": "Menu",
        "tare": "Tare",
        "send": "Send",
        "language": "Language",
        "cloud": "Cloud",
        "status": "Status",
        "create_profile": "Create",
        "profiles": "Profiles",
        "back": "Back",
        "select_profile": "Select",
        "edit_name": "Edit Name",
        "edit_g": "Edit g",
        "delete_profile": "Delete",
        "recalibration": "Recalib",
        "display_calibration": "Disp Cal",
        "display_calibration_hint1": "Run test_lcd_colors",
        "display_calibration_hint2": "Click/Long: Back",
        "edit_config": "Config",
        "config_edit_hint": "Clk:Next Lng:Save",
        "reset_config": "Reset Cfg",
        "confirm_delete": "Delete?",
        "buzzer_test": "Buzzer Test",
        "wifi_connecting": "WiFi Connecting",
        "wifi_ok": "WiFi OK",
        "wifi_fail": "WiFi Fail",
        "uploading": "Uploading",
        "upload_ok": "Upload OK",
        "upload_fail": "Upload Fail",
        "saved": "Saved",
        "error": "Error",
        "stable": "Stable",
        "settling": "Settling",
        "not_ready": "Unstable",
        "locked": "Locked",
        "english": "English",
        "hindi": "Hindi",
        "calibrate": "Calibrate",
        "cal_tare": "Empty Scale",
        "cal_place": "Place Weight",
        "cal_input": "Enter Weight",
        "cal_more": "Add More?",
        "cal_done": "Calibrated!",
        "cal_raw": "Raw",
        "cal_weight_n": "Weight #",
        "yes": "Yes",
        "no": "No",
    },
    "hi": {
        "title": "Tolan Yantra",
        "weight": "Vajan",
        "profile": "Profile",
        "gravity": "g",
        "menu": "Menu",
        "tare": "Tare",
        "send": "Bhejo",
        "language": "Bhasha",
        "cloud": "Cloud",
        "status": "Sthiti",
        "create_profile": "Naya Banao",
        "profiles": "Profiles",
        "back": "Wapas",
        "select_profile": "Chunein",
        "edit_name": "Naam Badlo",
        "edit_g": "g Badlo",
        "delete_profile": "Profile Hatao",
        "recalibration": "Dobara Calib",
        "display_calibration": "Display Jaach",
        "display_calibration_hint1": "test_lcd_colors chalao",
        "display_calibration_hint2": "Click/Long: Wapas",
        "edit_config": "Settings",
        "config_edit_hint": "Click:Agla Long:Save",
        "reset_config": "Sab Reset",
        "confirm_delete": "Mitana?",
        "buzzer_test": "Buzzer Jaach",
        "wifi_connecting": "WiFi Jud Raha",
        "wifi_ok": "WiFi Juda",
        "wifi_fail": "WiFi Asafal",
        "uploading": "Bhej Raha",
        "upload_ok": "Bhejna Safal",
        "upload_fail": "Bhejna Asafal",
        "saved": "Sangrahit",
        "error": "Truti",
        "stable": "Sthir",
        "settling": "Sthir Ho Raha",
        "not_ready": "Asthir",
        "locked": "Lock Hua",
        "english": "Angrezi",
        "hindi": "Hindi",
        "french": "French",
        "german": "German",
        "calibrate": "Calibrate Karo",
        "cal_tare": "Scale Khali Karo",
        "cal_place": "Vajan Rakho",
        "cal_input": "Vajan Dalo",
        "cal_more": "Aur Dalna?",
        "cal_done": "Calibration Pura!",
        "cal_raw": "Raw",
        "cal_weight_n": "Vajan #",
        "yes": "Haan",
        "no": "Nahi",
    },
    "fr": {
        "title": "Balance Poids",
        "weight": "Poids",
        "profile": "Profil",
        "gravity": "g",
        "menu": "Menu",
        "tare": "Tarer",
        "send": "Envoyer",
        "language": "Langue",
        "cloud": "Cloud",
        "status": "Etat",
        "create_profile": "Creer",
        "profiles": "Profils",
        "back": "Retour",
        "select_profile": "Choisir",
        "edit_name": "Nom Profil",
        "edit_g": "Modifier g",
        "delete_profile": "Supprimer",
        "recalibration": "Recalibrer",
        "display_calibration": "Calib Ecran",
        "display_calibration_hint1": "Lancer test_lcd_colors",
        "display_calibration_hint2": "Click/Long: Retour",
        "edit_config": "Config",
        "config_edit_hint": "Clk:Suiv Long:Save",
        "reset_config": "Reset Config",
        "confirm_delete": "Supprimer?",
        "buzzer_test": "Test Buzzer",
        "wifi_connecting": "Connexion WiFi",
        "wifi_ok": "WiFi OK",
        "wifi_fail": "WiFi Echec",
        "uploading": "Envoi...",
        "upload_ok": "Envoi OK",
        "upload_fail": "Envoi Echec",
        "saved": "Sauve",
        "error": "Erreur",
        "stable": "Stable",
        "settling": "Stabilise",
        "not_ready": "Instable",
        "locked": "Verrouille",
        "english": "Anglais",
        "hindi": "Hindi",
        "french": "Francais",
        "german": "Allemand",
        "calibrate": "Calibrer",
        "cal_tare": "Balance Vide",
        "cal_place": "Poser Poids",
        "cal_input": "Entrer Poids",
        "cal_more": "Ajouter Plus?",
        "cal_done": "Calibre!",
        "cal_raw": "Brut",
        "cal_weight_n": "Poids #",
        "yes": "Oui",
        "no": "Non",
    },
    "de": {
        "title": "Waage",
        "weight": "Gewicht",
        "profile": "Profil",
        "gravity": "g",
        "menu": "Menue",
        "tare": "Tara",
        "send": "Senden",
        "language": "Sprache",
        "cloud": "Cloud",
        "status": "Status",
        "create_profile": "Neu",
        "profiles": "Profile",
        "back": "Zurueck",
        "select_profile": "Auswahl",
        "edit_name": "Name Aendern",
        "edit_g": "g Aendern",
        "delete_profile": "Loeschen",
        "recalibration": "Neu Kalib",
        "display_calibration": "Display Kalib",
        "display_calibration_hint1": "test_lcd_colors starten",
        "display_calibration_hint2": "Click/Long: Zurueck",
        "edit_config": "Config",
        "config_edit_hint": "Clk:Next Lng:Save",
        "reset_config": "Reset Config",
        "confirm_delete": "Loeschen?",
        "buzzer_test": "Buzzer Test",
        "wifi_connecting": "WiFi Verbinde",
        "wifi_ok": "WiFi OK",
        "wifi_fail": "WiFi Fehler",
        "uploading": "Sende...",
        "upload_ok": "Senden OK",
        "upload_fail": "Senden Fehler",
        "saved": "Gespeichert",
        "error": "Fehler",
        "stable": "Stabil",
        "settling": "Beruhigt",
        "not_ready": "Instabil",
        "locked": "Gesperrt",
        "english": "Englisch",
        "hindi": "Hindi",
        "french": "Franzoesisch",
        "german": "Deutsch",
        "calibrate": "Kalibrieren",
        "cal_tare": "Waage Leer",
        "cal_place": "Gewicht Auflegen",
        "cal_input": "Gewicht Eingeben",
        "cal_more": "Mehr Hinzufuegen?",
        "cal_done": "Kalibriert!",
        "cal_raw": "Raw",
        "cal_weight_n": "Gewicht #",
        "yes": "Ja",
        "no": "Nein",
    },
}


def available_languages():
    return SUPPORTED_LANGUAGES


def normalize_language(language):
    if language in STRINGS:
        return language
    return DEFAULT_LANGUAGE


def tr(language, key):
    language = normalize_language(language)
    return STRINGS.get(language, {}).get(key, STRINGS[DEFAULT_LANGUAGE].get(key, key))
